<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=gbk" />
<title>我的主页 - 厨色网</title><meta name="keywords" content="我的主页 - 厨色" />
<meta name="description" content="我的主页 - 厨色" />
<link rel="stylesheet" type="text/css" href="//icon.qiantucdn.com/static/css/qt-ui_733c304cadef6428.css" />
<link rel="stylesheet" type="text/css" href="//icon.qiantucdn.com/static/css/userHome/userHome_288678807d4bdc72.css" />
<script type="text/javascript">
        var now = new Date();
        var beginTime = now.getTime();
        var b = 1;
        var stime = "1521709590";
        setInterval(function () {
            stime++;
        }, 1000);
</script>
</head>
<body version="v1.0"><input type="hidden" id="isSendAjaxUser" value="1">
<div class="qt-tips" style="display:none;">
    <div class="w1200">您的<span class="vips_types">原创</span>VIP将在<span><span class="vips_days">7</span>天</span>后过期，每日下载数量及下载速度将受到限制。
    <a target="_blank"
                class="vips_jump_urls user_click_bth" data-ids="1">立即续费</a><i class="close-btn fr user_click_bth" data-ids="2"></i></div></div><div class="qt-header"><div class="qt-header-container clearfix qt-header-fixed"><div class="header-nav"><div class="search-fixed"><div class="search-main clearfix"><div class="btn-classify"><i class="icon icon-p-fenlei"></i>分类
                        </div><div class="fl search-input"><div><input type="text" class="fl" placeholder="9,600,200免费设计素材任意下载" value="" data-isShow="1" data-where="1" ></div></div><div class="qt-btn btn-green-linear btn-search fr"><i class="icon icon-p-search"></i></div><div class="search-result"></div><div class="search-classify"></div></div></div><div class="nav-wrap hover-box nav-fixed"><a href="javascript:;" class="arrow">
               
                   
                        &nbsp;
                    </a></div><div class="header-user info header-right fr"><div class="user-img"><a href="http://www.58pic.com/index.php?m=user&a=home" target="_blank"><img src="http://icon.qiantucdn.com/images/user/user-default.png" width="40" height="40" alt=""></a></div><div class="user-info js-copy-id"><p>ID:41347361<input type="text" id="cody-id" value="41347361"></p><p class="clearfix"></p></div><div class="header-drop"></div><input type="hidden" id="gx_vip_expireds" value="0"><input type="hidden" id="gx_vip_flags" value="0"><input type="hidden" id="yc_vip_expireds" value="0"><input type="hidden" id="yc_vip_flags" value="0"><input type="hidden" id="bg_vip_expireds" value="0"><input type="hidden" id="bg_vip_flags" value="0"><input type="hidden" id="public_user_id" value="41347361"></div><div class="messageSystem"><ul class="messageSystem-model"><span class="messageSystem-icon icon icon-p-ttpodicon"></span><span class="messageSystem-txt">消息</span><span class="messageSystem-base-info"></span></ul><span class="message-base-info"><span class="messageSystem-after" style="display:none"><li class="messageSystem-kong"><p class="messageSystem-kong-icon icon icon-p-ttpodicon"></p><p class="messageSystem-kong-txt">暂无消息</p></li><li class="messageSystem-link" style="margin-top:301px;"><a class="messageSystem-btn" href="javascript:;" data-info="0">全部标记为已读</a><a class="messageSystem-btn2" href="http://www.58pic.com/message/" target="_blank">全部信息</a></li></span></span><input type="hidden" id="isSendAjaxInfo" value="0"></div><div class="header-upload hover-box header-right fr"><i class="icon icon-p-shangchuan"></i><a href="http://www.58pic.com/index.php?m=upload&a=lists" target="_blank">
        上传
    </a></div><div class="header-vip hover-box header-right fr"><i class="icon icon-p-VIP"></i><a href="http://www.58pic.com/index.php?m=sponsor&a=intro&on=2" target="_blank">
        VIP
    </a><div class="header-drop clearfix"><div class="vip-wrap fl"><i class="icon-vip gx"></i><p>共享VIP</p><div class="qt-btn"><a href="http://www.58pic.com/index.php?m=sponsor&a=indexnew&f=4&t=3" target="_blank">
                        立即开通
                    </a></div></div><div class="vip-wrap fl"><i class="icon-vip yc"></i><p>原创VIP</p><div class="qt-btn"><a href="http://www.58pic.com/index.php?m=sponsor&a=indexnew&f=4&t=2" target="_blank">
                        立即开通
                    </a></div></div><div class="vip-wrap fl"><i class="icon-vip bg"></i><p>办公VIP</p><div class="qt-btn"><a href="http://www.58pic.com/index.php?m=sponsor&a=officeVip" target="_blank">
                        立即开通
                    </a></div></div><div class="vip-wrap fl"><i class="icon-vip super"></i><p>超级VIP</p><div class="qt-btn"><a href="http://www.58pic.com/index.php?m=sponsor&a=intro&on=2" target="_blank">
                    了解详情
                </a></div></div><div class="vip-wrap qy fl"><i class="icon-vip qy"></i><p>企业VIP</p><div class="qt-btn"><a href="http://www.58pic.com/introduce/" target="_blank">
                    了解详情
                </a></div></div></div></div></div></div></div><!--顶部简历弹窗模块 **********开始 --><!--顶部简历弹窗模块 **********结束 --><div class="user-myself-bg"><div class="w1200 user-header clearfix"><div class="user-box fl"><div class="user-img"><img src="http://icon.qiantucdn.com/images/user/user-default.png" width="86" height="86"></div></div><div class="user-resume fl"><p class="user-id">ID: 41347361</p><p class="user-name">浮夸<span class="vip-info"></span></p><p><span><i class="icon-secrecy"></i>保密</span><span><i class="icon-time"></i>注册于2018/03/22</span><span class="perf-info"><a href="http://www.58pic.com/index.php?m=user&a=accountSet">完善信息</a>可获取大量曝光
                    </span></p></div><div class="user-info fr"><a href="http://www.58pic.com/index.php?m=user&a=home&type=gz"><p><span>关注</span><em>0</em></p></a><p><span>粉丝</span><em>0</em></p><a href="http://www.58pic.com/index.php?m=user&a=home"><p><span>作品</span><em>0</em></p></a></div></div></div><div class="user-main clearfix w1200"><ul class="user-nav fl"><li  ><a href=""><i class="icon-user"></i>个人中心</a></li><li ><a href="http://www.58pic.com/index.php?m=upload&a=lists"><i class="icon-upload"></i>我的上传</a></li><li class='on'><a href="http://www.58pic.com/index.php?m=user&a=home"><i class="icon-home"></i>我的主页</a></li><li  ><a href="http://www.58pic.com/index.php?m=user&a=userFav" ><i class="icon-love" ></i>我的收藏</a></li><li  ><a href="http://www.58pic.com/index.php?m=user&a=resume" ><i class="icon-resume"></i>私信</a></li><li  ><a href="http://www.58pic.com/index.php?m=user&a=userDl" ><i class="icon-download"></i>我的下载</a></li><li  ><a href="http://www.58pic.com/index.php?m=user&a=vipRecord" ><i class="icon-vip"></i>我的VIP</a></li><li><a href="http://www.58pic.com/invite/"><i class="icon-company"></i>企业VIP</a></li><li  ><a href="http://localhost:8080/SimpleShopping/xinxi.html" ><i class="icon-set"></i>个人设置</a></li><li  ><a href="http://www.58pic.com/message/" ><i class="icon-message"></i>消息中心</a></li></ul><div class="main-container home-main clearfix fr"><div class="home-nav"><a href="http://www.58pic.com/index.php?m=user&a=home&type=sj" class="nav-list on">上传菜品 <em>(0)</em></a><a href="http://www.58pic.com/index.php?m=user&a=home&type=bg" class="nav-list ">关注我的 <em>(0)</em></a><a href="http://www.58pic.com/index.php?m=user&a=home&type=gz" class="nav-list ">我的关注 <em>(0)</em></a></div><div class="user-box-row"><div class="home-null-o home-other "><div class="home-null-alert"><div class="icon-box"></div><p class="alert-text">
                                您还没有上传任何菜
                                <br>去和大家分享您的菜吧~
                            </p><p class="qt-btn btn-green-linear"><a href="http://upload.58pic.com/">立即上传</a></p></div></div></div><div class="qt-pagination"></div></div></div><div class="qt-footer-default"><div class="w1200 qt-footer"><div class="footer-top clearfix"><dl class="fl"><dt>常见问题</dt><dd><a href="http://www.58pic.com/index.php?m=ogcintro" target="_blank" rel="nofollow">成为做菜小达人</a></dd><dd><a href="http://www.58pic.com/index.php?m=ogcintro" target="_blank" rel="nofollow">成为小小美食家</a></dd><dd><a href="http://www.58pic.com/index.php?m=HelpCenter&type2=1" target="_blank" rel="nofollow">注册登录</a></dd><dd><a href="http://www.58pic.com/index.php?m=HelpCenter&type2=3" target="_blank" rel="nofollow">帐号/密码</a></dd><dd><a href="http://www.58pic.com/index.php?m=HelpCenter&type2=2" target="_blank" rel="nofollow">充值/售后</a></dd><dd><a href="http://www.58pic.com/index.php?m=HelpCenter&a=addQuestion" target="_blank" rel="nofollow">版权投诉</a></dd></dl><dl class="fl"><dt>关于厨色网</dt><dd><a href="http://www.58pic.com/index.php?m=AboutUsNew" target="_blank" rel="nofollow">关于我们</a></dd><dd><a href="http://www.58pic.com/index.php?m=AboutUsNew&a=media" target="_blank" rel="nofollow">媒体报道</a></dd><dd><a href="http://www.58pic.com/index.php?m=AboutUsNew&a=joinUs" target="_blank" rel="nofollow">加入我们</a></dd><dd><a href="http://www.58pic.com/xinxiqiantu/" target="_blank" rel="nofollow">心系厨色</a></dd><dd><a href="http://www.58pic.com/?m=alliance" target="_blank" rel="nofollow">Q群联盟</a></dd></dl><dl class="fl"><dt>产品服务</dt><dd><a href="http://www.58pic.com/blog/" target="_blank" >官方微博</a></dd><dd><a href="http://www.58pic.com/index.php?m=HelpCenter" target="_blank" rel="nofollow">帮助中心</a></dd></dl><div class="fr other-service"><p class="service-title"><a href="javascript:void(0);" rel="external nofollow">客服咨询</a></p><p class="service-tel"><i></i>                   15732116236
                    <em>（9:00-18:00）</em></p><p class="service-email"><i></i><a href="mailto:feedback@58pic.com" rel="external nofollow">734034594@qq.com</a></p><p class="qt-btn btn-green-linear service-qq"><a onclick="javascript:window.open('http://wpa.b.qq.com/cgi/wpa.php?ln=2&uin=4009987011&eid=218808P8z8p8y8z8R8x8p&o=www.58pic.com&q=7&ref='+document.location, '_blank', 'height=544, width=644,toolbar=no,scrollbars=no,menubar=no,status=no');"
                        rel="external nofollow"><i></i>点我交谈
                    </a></p></div></div><div class="footer-bottom clearfix"><p class="fl bottom-icon"><a href="http://weibo.com/58pic" class="icon-sina" title="新浪" rel="external nofollow" target="_blank"></a><a href="javascript:void(0);" class="icon-wechat" title="微信" rel="external nofollow" target="_blank"><img src="http://icon.qiantucdn.com/img/searchnew/wechat-g.png" width="137" height="137" alt=""></a><!-- <a href="https://www.zhihu.com/people/qian-tu-wang-36" class="icon-quaro" title="知乎" target="_blank" rel="external nofollow"></a> -->                &nbsp;
            </p><p class="fl bottom-href"><a href="http://www.58pic.com/?m=links&a=announce" target="_blank" rel="external nofollow">注册声明</a><a href="http://www.58pic.com/copyright.html" target="_blank" rel="external nofollow">版权声明</a><a href="http://www.58pic.com/?m=links&a=customer" target="_blank" rel="external nofollow">售后服务</a></p><p class="fr">                Copyright &copy;2013-2018 厨色网<a href="http://www.miibeian.gov.cn" target="_blank" rel="external nofollow">冀ICP备10011451号-6</a><a href="http://218.242.124.22:8081/businessCheck/verifKey.do?showType=extShow&serial=9031000020160628142136000000987751-SAIC_SHOW_310000-20160828103425413778&signData=MEUCIFyxlqJ/q1F8aFaXEySVHaV1Kb8fbV1xCMDWUjGOFNFeAiEAjy6mDgN29T9mgHdtMwCUNDTiFOsj7hR/sXmyohemLDI="
                    target="_blank" rel="external nofollow"><i class="icon-badge"></i></a>
            </p></div></div></div><!--编辑弹窗--><div class="qt-model-t model-favirite-all" id="favirite-all"><div class="mdoel-table"><div class="model-table-call"><div class="model-content"><span class="model-table-close">&times;</span><div class="model-title">
                    添加到收藏夹
                    <!--<a href="http://www.58pic.com/index.php?m=Blog&a=detail&blog=118" target="_blank" style="color:#ff3b2e;"> 领取30天原创VIP >></a>--></div><ul class="favirite-box"></ul><div class="favirite-create"><a href="javascript:;" class="j-model-fav-create" data-model='{"target":"#favirite-create"}'><i class="icon-add"></i>创建收藏夹
                    </a><!--<p class="favorite-error-msg"></p>--></div><div class="btn-group"><p class="qt-btn btn-green-linear fav-ajax" data-id=""><a href="javascript:;">确认</a></p><p class="qt-btn btn-green"><a href="javascript:;" class="j-close">取消</a></p></div></div></div></div></div><!-- 空弹窗 --><div class="qt-model-t model-favirite-all" id="favirite-null"><div class="mdoel-table"><div class="model-table-call"><div class="model-content fav-null"><span class="model-table-close">&times;</span><div class="icon-null"></div><p class="p1">
                    您还未创建收藏夹，点击创建增加新收藏夹吧！
                </p><p class="p2">
                    您创建的收藏会显示在此处
                </p><p class="qt-btn btn-green-linear j-model-fav-create" data-model='{"target":"#favirite-create"}'><a href="javascript:;">创建收藏夹</a></p></div></div></div></div><!-- 创建弹窗 --><div class="qt-model-t model-favirite-all" id="favirite-create"><div class="mdoel-table"><div class="model-table-call"><div class="model-content"><span class="model-table-close">&times;</span><div class="model-title">
                    创建到收藏夹
                </div><div class="fav-create"><input type="text" value="" class="fav-name" placeholder="请输入收藏夹名称(3到10个字)"></div><div class="btn-group"><p class="qt-btn btn-green-linear"><a href="javascript:;" id="add-page" data-id="">创建</a></p><p class="qt-btn btn-green"><a href="javascript:;" class="j-close">取消</a></p></div></div></div></div></div><input type="hidden" data-page-count="0" class="favor-page-baseinfo"><!--收藏成功弹窗--><div class="public-popbox" id="favirite-success" style="display: none"><div class="alert-con"><i class="icont-true"></i><p></p></div></div><div class="public-popbox" id="favirite-error" style="display: none"><div class="alert-con"><i class="icont-error"></i><p></p></div></div><input type="hidden" id="h_type" value="sj" /><noscript><img height="1" width="1" style="display:none" src="https://a.gdt.qq.com/pixel?user_action_set_id=1106614899&action_type=PAGE_VIEW&noscript=1" /></noscript><script type="text/javascript" src="//icon.qiantucdn.com/static/js/qt-ui_4bbf4720458fc36e.js"></script><script type="text/javascript" data-loader src="//icon.qiantucdn.com/static/js/userHome/addon_c5a6e5aadf67ce9b.js"></script><script type="text/javascript" src="//icon.qiantucdn.com/static/js/userHome/userHome_f37484e67f9c01a0.js"></script></body></html>