var supe_uid='';var recipeid=$("#recipe_id").val();var islik=0;var isfav=0;$(".recipeCategory_sub_R b").each(function(){if($(this).html().length>10)
$(this).css("font-size","14px");else if($(this).html().length>8)
$(this).css("font-size","16px");});$.get(msc.tools.getAjaxUrl({ac:"user",op:"getrecipeloadinfo"}),{'id':recipeid},function(d){supe_uid=d.supe_uid;$(".J_lik span").text(d.likenum).after('人');$(".J_fav span").text(d.ratnum).after('人');if(d.islikecount==1){$(".J_lik").addClass('on').attr('title','已喜欢');islik=1;}
if(d.rc>0){$(".J_fav").addClass('on').attr('title','已收藏');isfav=1;}
if(d.kanshow){var kankanhtml='<div class="kanbox mt10"><a target="_blank" href="'+d.kanshow["pcurl"]+'"><div class="kanpic"><img width="100" height="100" src="'+d.kanshow["pic"]+'"></div><div class="kandetail"><h4>'+d.kanshow["subject"]+'</h4><div>'+d.kanshow["message"]+'</div><p>'+d.kanshow["note"]+'</p></div><div class="kanactive"><div class="kankan">看看</div></div></a></div>';$(".recipeArction").eq(0).before(kankanhtml);}
getRecipeDetailPaiandHealth();},"json");$("#recipe_De_imgBox").hover(function(){$("p.J_photo").fadeTo(0,0.7);},function(){$("p.J_photo").hide();});window._bd_share_config={"common":{"bdSnsKey":{"tsina":"3258795188","tqq":"208157"},"bdUrl":"//m.meishichina.com/recipe/"+recipeid+"/","bdText":"《"+$("#recipe_title").html()+"》，来自#厨色#的原创菜谱，作者:"+$("#recipe_username").html()+"，详细做法:","bdMini":"2","bdMiniList":false,"bdPic":$("#recipe_De_imgBox").find('img').attr('src'),"bdStyle":"0","bdSize":"16","bdWbuid":"1642625033"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='//static.meishichina.com/v6/js/lib/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];$(".shar a").click(function(){var id=$(this).attr('data');document.getElementById(id).click();});$(".J_lik").click(function(){if(supe_uid==''||supe_uid==0||$(this).hasClass("on")){msc.user.login();return false;}
else{var subject=$("#recipe_title").html();var recipeuid=$("#recipe_uid").val();var recipeusername=$("#recipe_username").html();$.post('/ajax/ajax.php?ac=recipe&op=add_recipe_like',{id:recipeid},function(e){if(e.error==0){msc.ui.dialog.success("添加喜欢成功");$(".J_lik").addClass('on').attr('title','已喜欢');$(".J_lik span").html(parseInt($(".J_lik span").html())+1);}
else{return false;}},"json");}});$(".J_fav").click(function(){if(supe_uid==''||supe_uid==0||$(this).hasClass("on")){msc.user.login();return false;}
else{msc.user.set_fav_recipe(recipeid,function(data){if(data.error==0){msc.ui.dialog.success("添加收藏成功");$(".J_fav").addClass('on').attr('title','已收藏');$(".J_fav span").html(parseInt($(".J_fav span").html())+1);return true;}else{msc.ui.dialog.error("操作失败请重试！")}},function(){if(!navigator.onLine){msc.ui.dialog.error("请先链接网络！");return;}
msc.ui.dialog.error("操作失败请重试！")});}});$(window).scroll(function(){var omng=$(".keyshow").eq(0).offset();var jtl=$("#smnbk").offset();if(omng.top<$(document).scrollTop()+40){$(".keyshow").css({position:"fixed",top:40,margin:0,left:omng.left});}else if(omng.top<jtl.top+10){$(".keyshow").css({position:"static",margin:"20px 0 0 0"});}
if($(document).scrollTop()>300&&$("#getRecommendNewRecipe_a").attr('page')==1){gettimeline();$("#getRecommendNewRecipe").parent().removeClass('left3_list').removeClass('ui_newlist_1').removeClass('mt20').addClass('timeline')}});msc.tools.comment({element:$("#comment"),data:{id:$("#recipe_id").val(),idtype:'recipe'}});$(".J_photo").click(function(){msc.ui.lookImg({title:$("#recipe_title").html(),index:0,data:J_photo,type:'mainpic'});});$(".J_col").click(function(){if(supe_uid==''||supe_uid==0){msc.user.login();return false;}
var content='';var content_xm='';$.get(msc.tools.getAjaxUrl({ac:"collect",op:"get_curuser_collect_list"}),{type:'recipe'},function(d){if(d.error==0){if(d.data2!=0)
content_xm='<div class="line" id="find_collect_div">菜单名称：&nbsp;<input type="text" id="find_collect"><div id="find_collectlist"><ul>'+d.data2+'</ul></div></div>';content='<div id="addtocollect"><div class="line">选择菜单：&nbsp;<select id="mycollect_list" data-width="120"><option value="">请选择</option>'+d.data+'</select><a href="https://member.meishichina.com/center/collect-add/" target="_blank">创建新菜单</a></div>'+content_xm+'<div class="line">设置排序：&nbsp;<select id="mycollect_order" data-width="120"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option></select><span class="gay">1-9,数字越大越靠前</span></div><div class="line">评论菜谱：&nbsp;<textarea class="" id="mycollect_info">这个菜谱怎么样？说说你的看法</textarea></div></div>';msc.ui.dialog({content:[content],lock:true,width:'400px',title:"加入到菜单",button:[{value:"确定",highlight:!0,callback:function(){var self=this;var collectid=$("#mycollect_list").val(),mid=$("#recipe_id").val(),idtype='recipe',unote=$("#mycollect_info").val(),weight=$("#mycollect_order").val();if(collectid==""){msc.ui.dialog.error("请选择您要加入的菜单");return false;}
if(weight=='')
weight=1;if(!/color_5b/.test($("#mycollect_info").attr('class')))
unote='';$.get(msc.tools.getAjaxUrl({ac:"collect",op:"add_collect"}),{collectid:collectid,mid:mid,idtype:idtype,unote:unote,weight:weight},function(d){if(d.error==0){msc.ui.dialog.loading();setTimeout(function(){msc.ui.dialog.loading.close();self&&self.close();msc.ui.dialog.success("添加成功",3000);},1000)}else if(d.error==-1){msc.ui.dialog.loading();setTimeout(function(){msc.ui.dialog.loading.close();self&&self.close();msc.ui.dialog.error("该菜谱已经存在于这个菜单中",3000);},1000)}else{msc.ui.dialog.error("出现异常，请重试");}},"json");return false;}}],cancel:function(){return true;},initialize:function(){msc.ui.select({id:"#mycollect_list",width:function(){if($("#mycollect_list").width()<80)
return 80;else
return $("#mycollect_list").width()>218?218:$("#mycollect_list").width();},defaultValue:true});msc.ui.select({id:"#mycollect_order",width:80,defaultValue:true});}});}else{msc.ui.dialog.error("发生异常，请重试");}},"json");});$("body").on("keyup paste","#find_collect",function(){var word;if($(this).val()!=' '&&$(this).val()!=''){word=$(this).val();$("#find_collectlist").show();$("#find_collectlist li").each(function(){if($(this).html().indexOf(word)>=0)
$(this).show();else
$(this).hide();});}else{$("#find_collectlist").hide();}});$("body").on("click","#find_collectlist li",function(){$("#find_collect").val($(this).html());$("#find_collectlist").hide();$("#mycollect_list").val($(this).attr("data-id")).change();});$("body").on("focus","#mycollect_info",function(){if(!/color_5b/.test($(this).attr('class')))
$(this).html("").val("").addClass('color_5b');});$("body").on("blur","#mycollect_info",function(){if($(this).val()=='')
$(this).val('这个菜谱怎么样？说说你的看法').removeClass('color_5b');});function gettimeline(){var ac=$("#getRecommendNewRecipe_a");if(ac.hasClass('on'))
return false;else{var page=ac.attr("page");ac.addClass("on");$.get("/ajax/ajax.php?ac=admobile&op=getTimeLineList",{page:page},function(d){if(d.data.length>0){var data='',i;for(i=0;i<d.data.length;i++){if(d.data[i].templetid==1){data+='<li class="t1"><a target="_blank" href="'+gethref(d.data[i])+'" class="clear"><div><b><img src="'+d.data[i].pic640+'"></b></div><h2>'+d.data[i].subject+'</h2><p>'+d.data[i].description+'</p><span>'+d.data[i].remark+'</span></a></li>';}
else if(d.data[i].templetid==2){data+='<li class="t2"><a target="_blank" href="'+gethref(d.data[i])+'">'+(d.data[i].subject!=''?'<h2>'+d.data[i].subject+'</h2>':'')+(d.data[i].description!=''?'<p>'+d.data[i].description+'</p>':'')+'<div><b><img src="'+d.data[i].picset[0]+'"></b></div><div><b><img src="'+d.data[i].picset[1]+'"></b></div><div><b><img src="'+d.data[i].picset[2]+'"></b></div><div><b><img src="'+d.data[i].picset[3]+'"></b></div>'+(d.data[i].remark!=''?'<span>'+d.data[i].remark+'</span>':'')+'</a></li>';}
else if(d.data[i].templetid==3){data+='<li class="t3"><a target="_blank" href="'+gethref(d.data[i])+'">'+'<div '+(d.data[i].type=='video'?'class="video"':'')+'><b style="padding-bottom:'+(d.data[i].shownum*100)+'%;"><img src="'+(d.data[i].picset.length>0?d.data[i].picset[0]:d.data[i].pic)+'"></b></div>'+(d.data[i].subject!=''?'<h2>'+d.data[i].subject+'</h2>':'')+(d.data[i].description!=''?'<p>'+d.data[i].description+'</p>':'')+(d.data[i].remark!=''?'<span>'+d.data[i].remark+'</span>':'')+'</a></li>';}}
$("#getRecommendNewRecipe").append(data);ac.attr('page',parseInt(page)+1);ac.removeClass("on");if(page>9)
ac.parent().hide();}
else{ac.removeClass("on");return false;}},"json")}}
$("#getRecommendNewRecipe_a").click(function(){gettimeline();});function gethref(e){var t='javascript:void(0);';switch(e.type)
{case'url':t=e.pcurl;break;case'collect':t='https://home.meishichina.com/collect-'+e.subid+'.html';break;case'recipe':t='https://home.meishichina.com/recipe-'+e.subid+'.html';break;case'pai':t='https://home.meishichina.com/pai-'+e.subid+'.html';break;case'event':t='https://home.meishichina.com/event-'+e.subid+'.html';break;case'mofang':t='https://www.meishichina.com/mofang/'+e.subid+'/';break;case'zhen':t='https://zhen.meishichina.com/'+e.subid+'/';break;case'listing':t='https://zhen.meishichina.com/listing/'+e.subid+'/';break;case'video':t='https://home.meishichina.com/video-'+e.subid+'.html';break;case'article':t=e.pcurl;break;default:t='javascript:void(0);';}
return t;}
function getRecipeDetailPaiandHealth(){$.get('/ajax/ajax.php?ac=recipe&op=getRecipeDetailPaiandHealth',{rid:recipeid,ingredient:$("#getRecipeDetailPaiandHealth").attr('ingredient')},function(d){var i,j,html_pai='',html_health='',html='';if(d.error==0){for(i=0;i<d.paidata.length;i++){html_pai+='<li><a href="https://home.meishichina.com/pai-'+d.paidata[i]["id"]+'.html" target="_blank"><img src="'+d.paidata[i]["cover"]+'" ><p class="t1">'+(d.paidata[i]["title"]?d.paidata[i]["title"]:'')+'</p><p class="t2">'+(d.paidata[i]["subject"]?d.paidata[i]["subject"]:'')+'</p></a></li>';}
for(j=0;j<d.healthdata.length;j++){html_health+='<p><a title="'+d.healthdata[j]["Title"]+'" href="'+d.healthdata[j]["ArticleLink"]+'" target="_blank">'+d.healthdata[j]["Title"]+'</a></p>'}
if(html_pai!='')
html+='<div class="recipe_rlist clear"><ul>'+html_pai+'</ul></div>';if(html_health!='')
html+='<div class="tuijian">'+html_health+'</div>';$("#getRecipeDetailPaiandHealth").append('<div class="ui_title mt20 clear"><div class="ui_title_wrap"><h3 class="on">健康与话题</h3><a title="饮食健康" href="https://www.meishichina.com/Health/" class="right" target="_blank">更多</a></div></div>'+html);}},"json");}